2019-06-05T09:58:35|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "microscope_app.py", line 33, in <module>
    app = OceanOpticsApp(sys.argv)
  File "C:\Users\lindat18\AppData\Local\Continuum\miniconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 338, in __init__
    self.setup()
  File "microscope_app.py", line 17, in setup
    self.add_hardware(PiezoStageHardware(self))
NameError: name 'PiezoStageHardware' is not defined

