2019-06-05T14:29:36|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "Microscope_app.py", line 33, in <module>
    app = OceanOpticsApp(sys.argv)
  File "C:\Users\lindat18\AppData\Local\Continuum\miniconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 338, in __init__
    self.setup()
  File "Microscope_app.py", line 16, in setup
    from HW_PI_PiezoStage.PiezoStage_hardware import PiezoStageHW
ModuleNotFoundError: No module named 'HW_PI_PiezoStage'

